preset: symfony

enabled:
  - short_array_syntax
  - phpdoc_order
  - phpdoc_indent

disabled:
  - simplified_null_return

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  path:
    - "lib"
    - "src"
