---

##
# This file is part of the `src-run/augustus-utility-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

# Set the required project language environment and advise
# Travis that this project fully supports the new, speedy,
# container-built infrastructure.
language : php
sudo     : false

# Build against the following engines: Zend 5.6.x, 7.0.x, and
# 7-nightly, and HHVM-stable and -nightly builds.
php :
  - 5.6
  - 7.0

# Set a sane clone depth for Git.
git :
  depth : 3

# Add custom Hostname to build environment.
addons :
  hosts :
    - mainline.src.run

# Define any required global enviornment variables. Specifically,
# the package_builder variable must be set to true to enable the
# automated package builder scripts.
env :
  global :
    - build_package=true

# Use builder to install system environment and application 
# requirements.
install :
  - bash .config/builders/build-reqs/build-reqs.bash up-env
  - bash .config/builders/build-reqs/build-reqs.bash up-app

# Run unit tests!
script : bin/phpunit -vvv

# Use builder to run post-operations, most importantly handle
# statistics submissions for text coverage.
after_script :
  - bash .config/builders/build-reqs/build-reqs.bash dn-app
  - bash .config/builders/build-reqs/build-reqs.bash dn-env

...
